name: Compile and Release PDFs

permissions:
  contents: write

on:
  push:
    branches:
      - main

    paths:
      - '**.typ'

jobs:
  compile-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/download/v0.11.0/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
          tar -xf typst.tar.xz
          sudo mv typst-*/typst /usr/local/bin/
      
      - name: Compile Typst files
        run: |
          for file in *.typ; do
            # skip Template.typ
            if [ "$file" = "template.typ" ]; then
              continue
            fi
            typst compile "$file" "${file%.typ}.pdf"
            typst compile "$file" "${file%.typ}.png"
          done

      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.pdf *.png'
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
